require 'json'

platform :ios do
  desc "Build and export the app IPA"
  lane :build_app do
    build_app(
      scheme: "DemoApp",
      export_method: "development",
      output_directory: "./output"
    )
  end

  desc "Build and export the test runner IPA"
  lane :build_test_runner do
    build_app(
      scheme: "DemoAppUITests",
      export_method: "development",
      output_directory: "./output"
    )
  end

  desc "Upload IPA to Sauce Labs"
  lane :upload_to_sauce_labs do |options|
    ipa_path = options[:ipa_path]
    test_ipa_path = options[:test_ipa_path]

    app_response = sh("curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST -H 'Content-Type: application/octet-stream' https://api.us-west-1.saucelabs.com/v1/storage/upload --data-binary @#{ipa_path}")
    test_response = sh("curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST -H 'Content-Type: application/octet-stream' https://api.us-west-1.saucelabs.com/v1/storage/upload --data-binary @#{test_ipa_path}")

    app_id = JSON.parse(app_response)["item"]["id"]
    test_id = JSON.parse(test_response)["item"]["id"]

    sh "echo 'SAUCE_STORAGE_URL_APP=storage:#{app_id}' >> sauce.env"
    sh "echo 'SAUCE_STORAGE_URL_TEST=storage:#{test_id}' >> sauce.env"
  end

  desc "Run XCUITest on Sauce Labs"
  lane :run_xcuitest do
    sh "source sauce.env"
    sh "saucectl run --config ./sauce.config.yml --username $SAUCE_USERNAME --accessKey $SAUCE_ACCESS_KEY"
  end
end
